name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-windows:
    name: CI (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Restore dependencies
      run: |
        dotnet tool restore
        dotnet paket restore
        yarn install
    - name: Build
      run: dotnet fake build -t Build
    - name: Pack
      run: dotnet fake build -t Pack
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fsharp.system.io-windows
        path: artifacts
    - name: Test
      run: dotnet fake build -t Test